server:
  port: 9030
  error:
    include-message: always
    whitelabel:
      enabled: false
redis:
  host: redis-17415.c257.us-east-1-3.ec2.cloud.redislabs.com
  port: 17415
  password: vcars73
spring:
  application:
    name: ib-api-dummies
  security:
    user:
      name: "ibpunyauser"
      password: "ib.punya#user@123"
  datasource:
    url: "jdbc:postgresql://ec2-23-22-191-232.compute-1.amazonaws.com:5432/d90p0hkv1nogrg"
    username: grkekqfyjbjmua
    password: e9ebb621d126129f1d37ec2342ad92a0f9d7c4978e07678c396403b2909cdc0c
    driver-class-name: org.postgresql.Driver
    platform: postgres
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true
        order_updates: true
        batch_versioned_data: true
        jdbc.batch_size: 1000
  quartz:
   job-store-type: jdbc
   jdbc:
     initialize-schema: always
   properties:
     org:
       quartz:
         scheduler:
           instanceName: website-ojk-qrtz
           instanceId: AUTO
         threadPool:
           class: org.quartz.simpl.SimpleThreadPool
           threadCount: 25
           threadPriority: 9
         jobStore:
           misfireThreshold: 600000
           class: org.quartz.impl.jdbcjobstore.JobStoreTX
           driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
           useProperties: false
           tablePrefix: qrtz_
           isClustered: true
           clusterCheckinInterval: 20000
ib:
  jwt:
    expiration: 7200
    secret: "cv.!@aLgamx_#"
  user:
    password : "gxHDS_#!x"
    session:
      login: 3600
      loginRemembered: 7200
      forgotPassword: 3600